# Generated by Django 5.2.6 on 2025-09-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='habitaciones',
            field=models.IntegerField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='casa',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
